import React, { useEffect } from 'react'
import './landingcomponent.css';
import Aos from 'aos';
import 'aos/dist/aos.css';
export default function Landingcomponent() {

    useEffect(() => {
        Aos.init({ duration: 2000 });
    }, [])
    return (

        <div>
            <div className="landingpagelorumipsum">


                <p className="parasa">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec
                    pretium sagittis justo, ac euismod purus semper vel.
                    In eget accumsan tortor, quis porta sapien.
                    Nam pellentesque ultricies turpis, sit amet tempor mi bibendum et. Proin ipsum felis,
                    volutpat sit amet enim sit amet, semper convallis elit. Pellentesque venenatis, dolor id iaculis aliquam, orci nisl maximus eros, eget dignissim tellus elit sit amet ante. Phasellus feugiat vestibulum nunc, eu laoreet nisl accumsan at. Nunc faucibus elit urna, et dictum diam blandit sit amet.

                    Donec sagittis sem ac enim porta tristique. Mauris lacinia ligula vitae eros condimentum, vel lobortis eros efficitur. Curabitur vitae viverra risus, vel pellentesque nisi. Donec ut semper orci. Curabitur vitae elementum arcu. Ut a tellus in nibh consequat commodo. Curabitur elit ligula, condimentum ac euismod ut, condimentum non lectus. Morbi et placerat purus. Etiam viverra pulvinar tempus. Sed tempus lorem eu eros tristique, et ornare urna luctus. Nunc consectetur ex eu ultrices congue.

                    Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut sodales enim eu lorem convallis molestie. Curabitur eget consequat dolor. Donec eu accumsan justo. Aliquam dolor mauris, porttitor id sem nec, aliquet molestie est. Phasellus justo nulla, hendrerit eu tellus ut, scelerisque eleifend ipsum. Duis efficitur velit a mauris pharetra iaculis. In vel tristique turpis.

                    Quisque ut mi sem. Quisque in mauris in enim fermentum sollicitudin dictum eget erat. Nunc nec vehicula lorem. Ut sed finibus lorem, sit amet sagittis purus. Aliquam congue ipsum sem, non commodo lacus aliquet facilisis. Curabitur orci ligula, lobortis vitae neque vel, maximus euismod nulla. Duis ultricies luctus bibendum. Sed maximus tortor a venenatis lacinia. Quisque egestas, tortor at posuere placerat, nisl nisl dapibus quam, sed condimentum justo urna eu odio. Etiam vulputate eros et ligula consectetur, condimentum rhoncus augue dignissim. In hendrerit luctus venenatis. Vestibulum ut nisi dictum, feugiat dui sit amet, porta nibh. Aenean sit amet ligula porta risus accumsan accumsan. Curabitur vulputate tincidunt orci sit amet fermentum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In posuere urna a ipsum sagittis aliquam.

                    lorem. Ut sed finibus lorem, sit amet sagittis purus. Aliquam congue ipsum sem, non commodo lacus aliquet facilisis. Curabitur orci ligula, lobortis vitae neque vel, maximus euismod nulla. Duis ultricies luctus bibendum. Sed maximus tortor a venenatis lacinia. Quisque egestas, tortor at posuere placerat, nisl nisl dapibus quam, sed condimentum justo urna eu odio. Etiam vulputate eros et ligula consectetur, condimentum rhoncus augue dignissim. In hendrerit luctus venenatis. Vestibulum ut nisi dictum, feugiat dui sit amet, porta nibh. Aenean sit amet ligula porta risus accumsan accumsan. Curabitur vulputate tincidunt orci sit amet fermentum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In posuere urna a ipsum sagittis aliquam.
                    condimentum rhoncus augue dignissim. In hendrerit luctus venenatis. Vestibulum ut nisi dictum, feugiat dui sit amet, porta nibh. Aenean sit amet ligula porta risus accumsan accumsan. Curabitur vulputate tincidunt orci sit amet fermentum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In posuere urna a ipsum sagittis aliquam.
                    Donec sagittis sem ac enim porta tristique. Mauris lacinia ligula vitae eros condimentum, vel lobortis eros efficitur. Curabitur vitae viverra risus, vel pellentesque nisi. Donec ut semper orci. Curabitur vitae elementum arcu. Ut a tellus in nibh consequat commodo. Curabitur elit ligula, condimentum ac euismod ut, condimentum non lectus. Morbi et placerat purus. Etiam viverra pulvinar tempus. Sed tempus lorem eu eros tristique, et ornare urna luctus. Nunc consectetur ex eu ultrices congue.

                    Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut sodales enim eu lorem convallis molestie. Curabitur eget consequat dolor. Donec eu accumsan justo. Aliquam dolor mauris, porttitor id sem nec, aliquet molestie est. Phasellus justo nulla, hendrerit eu tellus ut, scelerisque eleifend ipsum. Duis efficitur velit a mauris pharetra iaculis. In vel tristique turpis.

                    Quisque ut mi sem. Quisque in mauris in enim fermentum sollicitudin dictum eget erat. Nunc nec vehicula lorem. Ut sed finibus lorem, sit amet sagittis purus. Aliquam congue ipsum sem, non commodo lacus aliquet facilisis. Curabitur orci ligula, lobortis vitae neque vel, maximus euismod nulla. Duis ultricies luctus bibendum. Sed maximus tortor a venenatis lacinia. Quisque egestas, tortor at posuere placerat, nisl nisl dapibus quam, sed condimentum justo urna eu odio. Etiam vulputate eros et ligula consectetur, condimentum rhoncus augue dignissim. In hendrerit luctus venenatis. Vestibulum ut nisi dictum, feugiat dui sit amet, porta nibh. Aenean sit amet ligula porta risus accumsan accumsan. Curabitur vulputate tincidunt orci sit amet fermentum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In posuere urna a ipsum sagittis aliquam.

                    lorem. Ut sed finibus lorem, sit amet sagittis purus. Aliquam congue ipsum sem, non commodo lacus aliquet facilisis. Curabitur orci ligula, lobortis vitae neque vel, maximus euismod nulla. Duis ultricies luctus bibendum. Sed maximus tortor a venenatis lacinia. Quisque egestas, tortor at posuere placerat, nisl nisl dapibus quam, sed condimentum justo urna eu odio. Etiam vulputate eros et ligula consectetur, condimentum rhoncus augue dignissim. In hendrerit luctus venenatis. Vestibulum ut nisi dictum, feugiat dui sit amet, porta nibh. Aenean sit amet ligula porta risus accumsan accumsan. Curabitur vulputate tincidunt orci sit amet fermentum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In posuere urna a ipsum sagittis aliquam.
                    Donec sagittis sem ac enim porta tristique. Mauris lacinia ligula vitae eros condimentum, vel lobortis eros efficitur. Curabitur vitae viverra risus, vel pellentesque nisi. Donec ut semper orci. Curabitur vitae elementum arcu. Ut a tellus in nibh consequat commodo. Curabitur elit ligula, condimentum ac euismod ut, condimentum non lectus. Morbi et placerat purus. Etiam viverra pulvinar tempus. Sed tempus lorem eu eros tristique, et ornare urna luctus. Nunc consectetur ex eu ultrices congue.

                    Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut sodales enim eu lorem convallis molestie. Curabitur eget consequat dolor. Donec eu accumsan justo. Aliquam dolor mauris, porttitor id sem nec, aliquet molestie est. Phasellus justo nulla, hendrerit eu tellus ut, scelerisque eleifend ipsum. Duis efficitur velit a mauris pharetra iaculis. In vel tristique turpis.

                    Quisque ut mi sem. Quisque in mauris in enim fermentum sollicitudin dictum eget erat. Nunc nec vehicula lorem. Ut sed finibus lorem, sit amet sagittis purus. Aliquam congue ipsum sem, non commodo lacus aliquet facilisis. Curabitur orci ligula, lobortis vitae neque vel, maximus euismod nulla. Duis ultricies luctus bibendum. Sed maximus tortor a venenatis lacinia. Quisque egestas, tortor at posuere placerat, nisl nisl dapibus quam, sed condimentum justo urna eu odio. Etiam vulputate eros et ligula consectetur, condimentum rhoncus augue dignissim. In hendrerit luctus venenatis. Vestibulum ut nisi dictum, feugiat dui sit amet, porta nibh. Aenean sit amet ligula porta risus accumsan accumsan. Curabitur vulputate tincidunt orci sit amet fermentum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In posuere urna a ipsum sagittis aliquam.

                    lorem. Ut sed finibus lorem, sit amet sagittis purus. Aliquam congue ipsum sem, non commodo lacus aliquet facilisis. Curabitur orci ligula, lobortis vitae neque vel, maximus euismod nulla. Duis ultricies luctus bibendum. Sed maximus tortor a venenatis lacinia. Quisque egestas, tortor at posuere placerat, nisl nisl dapibus quam, sed condimentum justo urna eu odio. Etiam vulputate eros et ligula consectetur, condimentum rhoncus augue dignissim. In hendrerit luctus venenatis. Vestibulum ut nisi dictum, feugiat dui sit amet, porta nibh. Aenean sit amet ligula porta risus accumsan accumsan. Curabitur vulputate tincidunt orci sit amet fermentum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In posuere urna a ipsum sagittis aliquam.
                    Donec sagittis sem ac enim porta tristique. Mauris lacinia ligula vitae eros condimentum, vel lobortis eros efficitur. Curabitur vitae viverra risus, vel pellentesque nisi. Donec ut semper orci. Curabitur vitae elementum arcu. Ut a tellus in nibh consequat commodo. Curabitur elit ligula, condimentum ac euismod ut, condimentum non lectus. Morbi et placerat purus. Etiam viverra pulvinar tempus. Sed tempus lorem eu eros tristique, et ornare urna luctus. Nunc consectetur ex eu ultrices congue.

                    Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut sodales enim eu lorem convallis molestie. Curabitur eget consequat dolor. Donec eu accumsan justo. Aliquam dolor mauris, porttitor id sem nec, aliquet molestie est. Phasellus justo nulla, hendrerit eu tellus ut, scelerisque eleifend ipsum. Duis efficitur velit a mauris pharetra iaculis. In vel tristique turpis.

                    Quisque ut mi sem. Quisque in mauris in enim fermentum sollicitudin dictum eget erat. Nunc nec vehicula lorem. Ut sed finibus lorem, sit amet sagittis purus. Aliquam congue ipsum sem, non commodo lacus aliquet facilisis. Curabitur orci ligula, lobortis vitae neque vel, maximus euismod nulla. Duis ultricies luctus bibendum. Sed maximus tortor a venenatis lacinia. Quisque egestas, tortor at posuere placerat, nisl nisl dapibus quam, sed condimentum justo urna eu odio. Etiam vulputate eros et ligula consectetur, condimentum rhoncus augue dignissim. In hendrerit luctus venenatis. Vestibulum ut nisi dictum, feugiat dui sit amet, porta nibh. Aenean sit amet ligula porta risus accumsan accumsan. Curabitur vulputate tincidunt orci sit amet fermentum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In posuere urna a ipsum sagittis aliquam.

                    lorem. Ut sed finibus lorem, sit amet sagittis purus. Aliquam congue ipsum sem, non commodo lacus aliquet facilisis. Curabitur orci ligula, lobortis vitae neque vel, maximus euismod nulla. Duis ultricies luctus bibendum. Sed maximus tortor a venenatis lacinia. Quisque egestas, tortor at posuere placerat, nisl nisl dapibus quam, sed condimentum justo urna eu odio. Etiam vulputate eros et ligula consectetur, condimentum rhoncus augue dignissim. In hendrerit luctus venenatis. Vestibulum ut nisi dictum, feugiat dui sit amet, porta nibh. Aenean sit amet ligula porta risus accumsan accumsan. Curabitur vulputate tincidunt orci sit amet fermentum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In posuere urna a ipsum sagittis aliquam.
                    Donec sagittis sem ac enim porta tristique. Mauris lacinia ligula vitae eros condimentum, vel lobortis eros efficitur. Curabitur vitae viverra risus, vel pellentesque nisi. Donec ut semper orci. Curabitur vitae elementum arcu. Ut a tellus in nibh consequat commodo. Curabitur elit ligula, condimentum ac euismod ut, condimentum non lectus. Morbi et placerat purus. Etiam viverra pulvinar tempus. Sed tempus lorem eu eros tristique, et ornare urna luctus. Nunc consectetur ex eu ultrices congue.

                    Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut sodales enim eu lorem convallis molestie. Curabitur eget consequat dolor. Donec eu accumsan justo. Aliquam dolor mauris, porttitor id sem nec, aliquet molestie est. Phasellus justo nulla, hendrerit eu tellus ut, scelerisque eleifend ipsum. Duis efficitur velit a mauris pharetra iaculis. In vel tristique turpis.

                    Quisque ut mi sem. Quisque in mauris in enim fermentum sollicitudin dictum eget erat. Nunc nec vehicula lorem. Ut sed finibus lorem, sit amet sagittis purus. Aliquam congue ipsum sem, non commodo lacus aliquet facilisis. Curabitur orci ligula, lobortis vitae neque vel, maximus euismod nulla. Duis ultricies luctus bibendum. Sed maximus tortor a venenatis lacinia. Quisque egestas, tortor at posuere placerat, nisl nisl dapibus quam, sed condimentum justo urna eu odio. Etiam vulputate eros et ligula consectetur, condimentum rhoncus augue dignissim. In hendrerit luctus venenatis. Vestibulum ut nisi dictum, feugiat dui sit amet, porta nibh. Aenean sit amet ligula porta risus accumsan accumsan. Curabitur vulputate tincidunt orci sit amet fermentum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In posuere urna a ipsum sagittis aliquam.

                    lorem. Ut sed finibus lorem, sit amet sagittis purus. Aliquam congue ipsum sem, non commodo lacus aliquet facilisis. Curabitur orci ligula, lobortis vitae neque vel, maximus euismod nulla. Duis ultricies luctus bibendum. Sed maximus tortor a venenatis lacinia. Quisque egestas, tortor at posuere placerat, nisl nisl dapibus quam, sed condimentum justo urna eu odio. Etiam vulputate eros et ligula consectetur, condimentum rhoncus augue dignissim. In hendrerit luctus venenatis. Vestibulum ut nisi dictum, feugiat dui sit amet, porta nibh. Aenean sit amet ligula porta risus accumsan accumsan. Curabitur vulputate tincidunt orci sit amet fermentum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In posuere urna a ipsum sagittis aliquam.
       <span >
                        volutpat sit amet enim sit amet, semper convallis elit. Pellentesque venenatis, dolor id iaculis aliquam, orci nisl maximus eros, eget dignissim tellus elit sit amet ante. Phasellus feugiat vestibulum nunc, eu laoreet nisl accumsan at. Nunc faucibus elit urna, et dictum diam blandit sit amet.

                        Donec sagittis sem ac enim porta tristique. Mauris lacinia ligula vitae eros condimentum, vel lobortis eros efficitur. Curabitur vitae viverra risus, vel pellentesque nisi. Donec ut semper orci. Curabitur vitae elementum arcu. Ut a tellus in nibh consequat commodo. Curabitur elit ligula, condimentum ac euismod ut, condimentum non lectus. Morbi et placerat purus. Etiam viverra pulvinar tempus. Sed tempus lorem eu eros tristique, et ornare urna luctus. Nunc consectetur ex eu ultrices congue.

                        Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut sodales enim eu lorem convallis molestie. Curabitur eget consequat dolor. Donec eu accumsan justo. Aliquam dolor mauris, porttitor id sem nec, aliquet molestie est. Phasellus justo nulla, hendrerit eu tellus ut, scelerisque eleifend ipsum. Duis efficitur velit a mauris pharetra iaculis. In vel tristique turpis.

                        Quisque ut mi sem. Quisque in mauris in enim fermentum sollicitudin dictum eget erat. Nunc nec vehicula lorem. Ut sed finibus lorem, sit amet sagittis purus. Aliquam congue ipsum sem, non commodo lacus aliquet facilisis. Curabitur orci ligula, lobortis vitae neque vel, maximus euismod nulla. Duis ultricies luctus bibendum. Sed maximus tortor a venenatis lacinia. Quisque egestas, tortor at posuere placerat, nisl nisl dapibus quam, sed condimentum justo urna eu odio. Etiam vulputate eros et ligula consectetur, condimentum rhoncus augue dignissim. In hendrerit luctus venenatis. Vestibulum ut nisi dictum, feugiat dui sit amet, porta nibh. Aenean sit amet ligula porta risus accumsan accumsan. Curabitur vulputate tincidunt orci sit amet fermentum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In posuere urna a ipsum sagittis aliquam.

                        lorem. Ut sed finibus lorem, sit amet sagittis purus. Aliquam congue ipsum sem, non commodo lacus aliquet facilisis. Curabitur orci ligula, lobortis vitae neque vel, maximus euismod nulla. Duis ultricies luctus bibendum. Sed maximus tortor a venenatis lacinia. Quisque egestas, tortor at posuere placerat, nisl nisl dapibus quam, sed condimentum justo urna eu odio. Etiam vulputate eros et ligula consectetur, condimentum rhoncus augue dignissim. In hendrerit luctus venenatis. Vestibulum ut nisi dictum, feugiat dui sit amet, porta nibh. Aenean sit amet ligula porta risus accumsan accumsan. Curabitur vulputate tincidunt orci sit amet fermentum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In posuere urna a ipsum sagittis aliquam.
                        condimentum rhoncus augue dignissim. In hendrerit luctus venenatis. Vestibulum ut nisi dictum, feugiat dui sit amet, porta nibh. Aenean sit amet ligula porta risus accumsan accumsan. Curabitur vulputate tincidunt orci sit amet fermentum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In posuere urna a ipsum sagittis aliquam.
                        Donec sagittis sem ac enim porta tristique. Mauris lacinia ligula vitae eros condimentum, vel lobortis eros efficitur. Curabitur vitae viverra risus, vel pellentesque nisi. Donec ut semper orci. Curabitur vitae elementum arcu. Ut a tellus in nibh consequat commodo. Curabitur elit ligula, condimentum ac euismod ut, condimentum non lectus. Morbi et placerat purus. Etiam viverra pulvinar tempus. Sed tempus lorem eu eros tristique, et ornare urna luctus. Nunc consectetur ex eu ultrices congue.

                        Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut sodales enim eu lorem convallis molestie. Curabitur eget consequat dolor. Donec eu accumsan justo. Aliquam dolor mauris, porttitor id sem nec, aliquet molestie est. Phasellus justo nulla, hendrerit eu tellus ut, scelerisque eleifend ipsum. Duis efficitur velit a mauris pharetra iaculis. In vel tristique turpis.

                        Quisque ut mi sem. Quisque in mauris in enim fermentum sollicitudin dictum eget erat. Nunc nec vehicula lorem. Ut sed finibus lorem, sit amet sagittis purus. Aliquam congue ipsum sem, non commodo lacus aliquet facilisis. Curabitur orci ligula, lobortis vitae neque vel, maximus euismod nulla. Duis ultricies luctus bibendum. Sed maximus tortor a venenatis lacinia. Quisque egestas, tortor at posuere placerat, nisl nisl dapibus quam, sed condimentum justo urna eu odio. Etiam vulputate eros et ligula consectetur, condimentum rhoncus augue dignissim. In hendrerit luctus venenatis. Vestibulum ut nisi dictum, feugiat dui sit amet, porta nibh. Aenean sit amet ligula porta risus accumsan accumsan. Curabitur vulputate tincidunt orci sit amet fermentum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In posuere urna a ipsum sagittis aliquam.

                        lorem. Ut sed finibus lorem, sit amet sagittis purus. Aliquam congue ipsum sem, non commodo lacus aliquet facilisis. Curabitur orci ligula, lobortis vitae neque vel, maximus euismod nulla. Duis ultricies luctus bibendum. Sed maximus tortor a venenatis lacinia. Quisque egestas, tortor at posuere placerat, nisl nisl dapibus quam, sed condimentum justo urna eu odio. Etiam vulputate eros et ligula consectetur, condimentum rhoncus augue dignissim. In hendrerit luctus venenatis. Vestibulum ut nisi dictum, feugiat dui sit amet, porta nibh. Aenean sit amet ligula porta risus accumsan accumsan. Curabitur vulputate tincidunt orci sit amet fermentum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In posuere urna a ipsum sagittis aliquam.
                        Donec sagittis sem ac enim porta tristique. Mauris lacinia ligula vitae eros condimentum, vel lobortis eros efficitur. Curabitur vitae viverra risus, vel pellentesque nisi. Donec ut semper orci. Curabitur vitae elementum arcu. Ut a tellus in nibh consequat commodo. Curabitur elit ligula, condimentum ac euismod ut, condimentum non lectus. Morbi et placerat purus. Etiam viverra pulvinar tempus. Sed tempus lorem eu eros tristique, et ornare urna luctus. Nunc consectetur ex eu ultrices congue.

                        Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut sodales enim eu lorem convallis molestie. Curabitur eget consequat dolor. Donec eu accumsan justo. Aliquam dolor mauris, porttitor id sem nec, aliquet molestie est. Phasellus justo nulla, hendrerit eu tellus ut, scelerisque eleifend ipsum. Duis efficitur velit a mauris pharetra iaculis. In vel tristique turpis.

                        Quisque ut mi sem. Quisque in mauris in enim fermentum sollicitudin dictum eget erat. Nunc nec vehicula lorem. Ut sed finibus lorem, sit amet sagittis purus. Aliquam congue ipsum sem, non commodo lacus aliquet facilisis. Curabitur orci ligula, lobortis vitae neque vel, maximus euismod nulla. Duis ultricies luctus bibendum. Sed maximus tortor a venenatis lacinia. Quisque egestas, tortor at posuere placerat, nisl nisl dapibus quam, sed condimentum justo urna eu odio. Etiam vulputate eros et ligula consectetur, condimentum rhoncus augue dignissim. In hendrerit luctus venenatis. Vestibulum ut nisi dictum, feugiat dui sit amet, porta nibh. Aenean sit amet ligula porta risus accumsan accumsan. Curabitur vulputate tincidunt orci sit amet fermentum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In posuere urna a ipsum sagittis aliquam.

                        lorem. Ut sed finibus lorem, sit amet sagittis purus. Aliquam congue ipsum sem, non commodo lacus aliquet facilisis. Curabitur orci ligula, lobortis vitae neque vel, maximus euismod nulla. Duis ultricies luctus bibendum. Sed maximus tortor a venenatis lacinia. Quisque egestas, tortor at posuere placerat, nisl nisl dapibus quam, sed condimentum justo urna eu odio. Etiam vulputate eros et ligula consectetur, condimentum rhoncus augue dignissim. In hendrerit luctus venenatis. Vestibulum ut nisi dictum, feugiat dui sit amet, porta nibh. Aenean sit amet ligula porta risus accumsan accumsan. Curabitur vulputate tincidunt orci sit amet fermentum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In posuere urna a ipsum sagittis aliquam.
                        Donec sagittis sem ac enim porta tristique. Mauris lacinia ligula vitae eros condimentum, vel lobortis eros efficitur. Curabitur vitae viverra risus, vel pellentesque nisi. Donec ut semper orci. Curabitur vitae elementum arcu. Ut a tellus in nibh consequat commodo. Curabitur elit ligula, condimentum ac euismod ut, condimentum non lectus. Morbi et placerat purus. Etiam viverra pulvinar tempus. Sed tempus lorem eu eros tristique, et ornare urna luctus. Nunc consectetur ex eu ultrices congue.

                        Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut sodales enim eu lorem convallis molestie. Curabitur eget consequat dolor. Donec eu accumsan justo. Aliquam dolor mauris, porttitor id sem nec, aliquet molestie est. Phasellus justo nulla, hendrerit eu tellus ut, scelerisque eleifend ipsum. Duis efficitur velit a mauris pharetra iaculis. In vel tristique turpis.

                        Quisque ut mi sem. Quisque in mauris in enim fermentum sollicitudin dictum eget erat. Nunc nec vehicula lorem. Ut sed finibus lorem, sit amet sagittis purus. Aliquam congue ipsum sem, non commodo lacus aliquet facilisis. Curabitur orci ligula, lobortis vitae neque vel, maximus euismod nulla. Duis ultricies luctus bibendum. Sed maximus tortor a venenatis lacinia. Quisque egestas, tortor at posuere placerat, nisl nisl dapibus quam, sed condimentum justo urna eu odio. Etiam vulputate eros et ligula consectetur, condimentum rhoncus augue dignissim. In hendrerit luctus venenatis. Vestibulum ut nisi dictum, feugiat dui sit amet, porta nibh. Aenean sit amet ligula porta risus accumsan accumsan. Curabitur vulputate tincidunt orci sit amet fermentum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In posuere urna a ipsum sagittis aliquam.

                        lorem. Ut sed finibus lorem, sit amet sagittis purus. Aliquam congue ipsum sem, non commodo lacus aliquet facilisis. Curabitur orci ligula, lobortis vitae neque vel, maximus euismod nulla. Duis ultricies luctus bibendum. Sed maximus tortor a venenatis lacinia. Quisque egestas, tortor at posuere placerat, nisl nisl dapibus quam, sed condimentum justo urna eu odio. Etiam vulputate eros et ligula consectetur, condimentum rhoncus augue dignissim. In hendrerit luctus venenatis. Vestibulum ut nisi dictum, feugiat dui sit amet, porta nibh. Aenean sit amet ligula porta risus accumsan accumsan. Curabitur vulputate tincidunt orci sit amet fermentum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In posuere urna a ipsum sagittis aliquam.
                        Donec sagittis sem ac enim porta tristique. Mauris lacinia ligula vitae eros condimentum, vel lobortis eros efficitur. Curabitur vitae viverra risus, vel pellentesque nisi. Donec ut semper orci. Curabitur vitae elementum arcu. Ut a tellus in nibh consequat commodo. Curabitur elit ligula, condimentum ac euismod ut, condimentum non lectus. Morbi et placerat purus. Etiam viverra pulvinar tempus. Sed tempus lorem eu eros tristique, et ornare urna luctus. Nunc consectetur ex eu ultrices congue.

                        Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut sodales enim eu lorem convallis molestie. Curabitur eget consequat dolor. Donec eu accumsan justo. Aliquam dolor mauris, porttitor id sem nec, aliquet molestie est. Phasellus justo nulla, hendrerit eu tellus ut, scelerisque eleifend ipsum. Duis efficitur velit a mauris pharetra iaculis. In vel tristique turpis.

                        Quisque ut mi sem. Quisque in mauris in enim fermentum sollicitudin dictum eget erat. Nunc nec vehicula lorem. Ut sed finibus lorem, sit amet sagittis purus. Aliquam congue ipsum sem, non commodo lacus aliquet facilisis. Curabitur orci ligula, lobortis vitae neque vel, maximus euismod nulla. Duis ultricies luctus bibendum. Sed maximus tortor a venenatis lacinia. Quisque egestas, tortor at posuere placerat, nisl nisl dapibus quam, sed condimentum justo urna eu odio. Etiam vulputate eros et ligula consectetur, condimentum rhoncus augue dignissim. In hendrerit luctus venenatis. Vestibulum ut nisi dictum, feugiat dui sit amet, porta nibh. Aenean sit amet ligula porta risus accumsan accumsan. Curabitur vulputate tincidunt orci sit amet fermentum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In posuere urna a ipsum sagittis aliquam.

                        lorem. Ut sed finibus lorem, sit amet sag
           </span>
                </p>
            </div>


            <div className="lawtext" data-aos-duration="800" data-aos="fade-up">
                Current rules of the Bar Council of India impose restrictions on maintaining a web page and do not permit lawyers to provide information concerning their areas of practice.  Venalicium Digital is, therefore, constrained from providing any further information on this web page.

                The rules of the Bar Council of India prohibit law firms from soliciting work or advertising in any manner. By clicking on ‘I AGREE’, the user acknowledges that:

                The user wishes to gain more information about Venalicium Digital, its practice areas and its attorneys, for his/her own information and use;
                The information is made available/provided to the user only on his/her specific request and any information obtained or material downloaded from this website is completely at the user’s volition and any transmission, receipt or use of this site is not intended to, and will not, create any lawyer-client relationship; and
                None of the information contained on the website is in the nature of a legal opinion or otherwise amounts to any legal advice.
                Venalicium Digital , is not liable for any consequence of any action taken by the user relying on material/information provided under this website. In cases where the user has any legal issues, he/she in all cases must seek independent legal advice.
</div>

        </div>
    )
}
